### ISSUE TITLE
documentation not clear?

### ISSUE THREAD

**Issue by arademaker** [amir-zeldes/DepEdit#11] opened 2018-05-30 22:54 UTC
Given

```
4	por	por	ADP	PRP|@ADVL>	_	9	advmod	_	MWEPOS=ADV
5	exemplo	exemplo	NOUN	N|M|S|@P<	Gender=Masc|Number=Sing	4	fixed	_	ChangedBy=Issue165|SpaceAfter=No
```

The ini file

```
func!=/fixed/&text=/(.*)/&misc=/(.*)/;func=/fixed/&text=/(.*)/	#1>#2	#1:misc=$2|MWE=$1_$3
```

Why is the system producing the output below? I just one to 

```
4	por	por	ADP	PRP|@ADVL>	_	9	advmod	_	MWEPOS=ADV|MWE=MWEPOS=ADV_MWEPOS=ADV
5	exemplo	exemplo	NOUN	N|M|S|@P<	Gender=Masc|Number=Sing	4	fixed	_	ChangedBy=Issue165|SpaceAfter=No
```

The expected output was:

```
4	por	por	ADP	PRP|@ADVL>	_	9	advmod	_	MWEPOS=ADV|MWE=por_exemplo
5	exemplo	exemplo	NOUN	N|M|S|@P<	Gender=Masc|Number=Sing	4	fixed	_	ChangedBy=Issue165|SpaceAfter=No
```

**Comment by amir-zeldes** [comment] 2018-05-31 19:38
You are correct, this is a bug - thanks for reporting. I think I see where the problem is...

**Comment by amir-zeldes** [comment] 2018-05-31 19:49
@arademaker I think this should solve your issue - you can find the fixed version in the develop branch. I need to get around to making a new release on PyPI, so for now please replace your depedit.py with the dev version and let me know if you run into any bugs.

**Comment by arademaker** [comment] 2018-05-31 21:50
@amir-zeldes thank you, but I believe you introduce another minor bug. An input file, if no rule is applied to it, produces an output with one extra line in the end. I believe the output should be exactly the same of the input in that case, right?

Regarding feature request, it would be nice a log file showing the rules applied and the lines of the files that were affected.

**Comment by amir-zeldes** [comment] 2018-06-01 21:53
I see - I'm not entirely sure I want it to output exactly what it got in (e.g. files should end in a newline after the last token), but you're right that it shouldn't just repeatedly add lines. 

I'm realizing this is also an inconsistency between batch mode and single document, since single document uses Python `print`, which automatically adds a newline. So for consistency, I'll change this, and now all files will be outputted with as much trailing whitespace as entered, except that if they don't end in newline after the last token, one will be inserted. Does this solve your problem?

**Closed as completed** 2018-07-10 22:51 UTC
Labels: bug
